version: "3.7"
services:
  #
  # Microservices
  #
  identity:
    build: ./identity-service
    hostname: identity.alexandria.com
    image: alexandria-identity
    restart: on-failure
    volumes:
      - api:/usr/src/identity/
    ports:
      - "3000:8080"
      - "4000:31337"
    depends_on:
      - kafka
      - zipkin
    networks:
      - alexandria-tier

  author:
    build: ./author-service
    hostname: author.alexandria.com
    image: alexandria-author
    restart: on-failure
    volumes:
      - api:/usr/src/author/
    ports:
      - "3001:8080"
      - "4001:31337"
    depends_on:
      - postgres
      - redis
      - kafka
      - zipkin
    networks:
      - alexandria-tier

  media:
    build: ./media-service
    hostname: media.alexandria.com
    image: alexandria-media
    restart: on-failure
    volumes:
      - api:/usr/src/media/
    ports:
      - "3002:8080"
      - "4002:31337"
    depends_on:
      - postgres
      - redis
      - kafka
      - zipkin
    networks:
      - alexandria-tier

  blob:
    build: ./blob-service
    hostname: blob.alexandria.com
    image: alexandria-blob
    restart: on-failure
    volumes:
      - api:/usr/src/blob/
    ports:
      - "3003:8080"
    depends_on:
      - kafka
      - zipkin
    networks:
      - alexandria-tier


  #
  # Infrastructure
  #
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6380:6379"
    networks:
      - alexandria-tier

  postgres:
    image: "postgres:12.2-alpine"
    restart: on-failure
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=alexandria_author,alexandria_media
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./scripts/migrations/:/docker-entrypoint-initdb.d/
    networks:
      - alexandria-tier

  zipkin:
    image: "openzipkin/zipkin"
    restart: on-failure
    ports:
      - "9412:9411"
    networks:
      - alexandria-tier

  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: on-failure
    ports:
      - "2182:2181"
    environment:
      - ZOO_ENABLE_AUTH=no
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=root
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./third-party/zookeeper/:/bitnami/zookeeper
    networks:
      - alexandria-tier

  kafka:
    image: "bitnami/kafka:latest"
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=root
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
    volumes:
      - ./third-party/kafka/:/bitnami/kafka
    networks:
      - alexandria-tier


volumes:
  api:
    driver: local
  database_postgres:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  alexandria-tier:
      driver: bridge